### ISSUE TITLE
Basic Guest App Functionality

### ISSUE THREAD

**Issue by mobyvb** [jd-team-193/led-pathways#24]
# Guest App
Should receive employee data from the server by sending a GET request to `/api/employees`. Upon receiving this data, it should update the UI to list the employees. The guest should be able to select a specific employee to visit. At this point, the app should send a POST request to `/api/visit/<employeeID>` and update the UI to reflect the server's response.

On success, the server will send a `200` status code as well as information in the following format:
`{color: "red"}`
The tablet app should go to a view with a message that says "Follow the \<color\> path."

On failure, the server will send a `400` status code as well as information in the following format:
`{error: "error message"}`
The tablet app should display an error notification with the error message.

**Comment by mmccoy37** [comment]
currently have completed:
- JSON parsing
- AsyncTask to get employee info
- AsyncTask for employee image
- built ListView item with profile image, status, and name
- partial completion of filter function
