### ISSUE TITLE
Basic Employee App Functionality

### ISSUE THREAD

**Issue by mobyvb** [jd-team-193/led-pathways#25]
# Employee App
The app should send a GET request to `/api/employees/donotdisturb/<employeeID>` to get Do Not Disturb data for the app's owner. The view should be updated to reflect this information.

The app should send a POST request to `/api/employees/donotdisturb/<employeeID>` to update Do Not Disturb data for the app's owner.

Do Not Disturb data should be transmitted and received in the following format:
```
{
    timeBlocks: [
        {startTime: 1484958582109, endTime: 1484958598881},
        {startTime: 1484958620679, endTime: 1484958626047},
        ....
    ]
}
```

The server will respond with a 400 (Bad Request) status code if the format of the data sent is not valid.

The server will respond with a 401 (Unauthorized) status code if the device sending the information is not registered to the employee ID being modified.

Otherwise, the server will respond with a 200 (OK) status code, along with the updated Do Not Disturb information.

The employee app should display notifications upon receiving errors. Errors will be in this format:
`{error: "error message"}`

**Comment by ditchfieldcaleb** [comment]
Completed in Sprint 1.
