### ISSUE TITLE
Employee App Do Not Disturb and Location

### ISSUE THREAD

**Issue by mobyvb** [jd-team-193/led-pathways#27]
## Do Not Disturb
By Sprint 1, the employee app should already have functionality to send Do Not Disturb information the server. The goal in this sprint is to create an interface allowing the user to create and delete Do Not Disturb time blocks.

Verification for time blocks should be done both in the app and on the server, to prevent employees from creating overlapping or invalid time blocks.

## Location
The employee app should also deal with sending location data to the server. It should send a POST request to `/location/<employeeID>` to update that employee's location. It should be sent in the following format:
```
{lat: 50, lng: 50}
```

**Comment by ditchfieldcaleb** [comment]
Basic functionality complete. See #53 for some small location fixes.
