### ISSUE TITLE
Assign colors on server upon visitation request

### ISSUE THREAD

**Issue by mobyvb** [jd-team-193/led-pathways#57]
Keep track of six colors on the server: red, blue, green, orange, yellow, purple. When a successful visitation request comes through, respond to the request with one of these colors (which isn't currently in use). If all colors are in use upon a visitation request, respond with a 500 error.

The server should also make the color associated with a visitation request available ten minutes after that visitation request has occurred.

**Comment by mmccoy37** [comment]
@mobyvb  is this done?
