### ISSUE TITLE
Get communication between Raspberry Pi and Arduino working

### ISSUE THREAD

**Issue by mobyvb** [jd-team-193/led-pathways#59]
The Raspberry Pi and Arduino should be connected together and should be able to communicate via a serial connection. The Raspberry Pi should be able to send a color to the Arduino, and the Arduino should update the color of the LED strips accordingly.

**Comment by ditchfieldcaleb** [comment]
Calling this closed pending review, since I have written code that makes this work already. @mobyvb confirm?

**Comment by mmccoy37** [comment]
is this done
