### ISSUE TITLE
Get Arduino and LED strips working

### ISSUE THREAD

**Issue by mobyvb** [jd-team-193/led-pathways#60]
Get the Arduino to light up the LED strips with a single solid color. Once #59 and #58 are completed, this color should be the last color sent from the server. When the server expires the color being displayed by the Arduino, the Arduino should display another color that is not expired, or in the event that there are no colors in use, turn all the lights off.

**Comment by ditchfieldcaleb** [comment]
Calling this initially complete, since I have tested the code to do this; just not with the server interacting quite yet. @mobyvb closeable?

**Comment by mobyvb** [comment]
We can close it, but I'm gonna add stuff on the rasppi branch that also deals with this, at least for the time being

**Comment by mmccoy37** [comment]
so is this closed or no? can we close this? we could make a new issue for remaining things
