### ISSUE TITLE
Allow editing or deletion of user on admin portal

### ISSUE THREAD

**Issue by mmccoy37** [jd-team-193/led-pathways#81]
We should allow them to edit or delete users on the admin portal, right?

Would be easy to implement.

**Comment by mmccoy37** [comment]
@mobyvb or @willman54321  for sprint 5?

@willman54321 would you like to try? since moby and caleb will be working on the LED strip stuff?

**Comment by mobyvb** [comment]
I'm like 90% sure we had deletion at one point. Not sure what happened, but I'll look around.
